#!/usr/bin/env bash
# a script that install nginx and change default html
sudo apt-get update -y
sudo apt-get install nginx -y
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
service nginx restart
