#!/usr/bin/env bash
# a script that install nginx and change default html
sudo apt-get update -y
sudo apt-get install nginx -y
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
REDIRECT="\\\n\tlocation /redirect_me {\n\t\treturn 301 https://github.com/Bakijazzman;\n\t}\n"
sudo sed -i "53i $REDIRECT" /etc/nginx/sites-enabled/default
sudo nginx -s reload
