#!/usr/bin/env bash
# a script that install nginx and change default html
sudo apt-get update -y
sudo apt-get install nginx -y
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
redirect="\\\n\tlocation = /redirect_me {\n\t\t return 301 https://github.com/Bakijazzman;\n\t}\n"
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bakup
sudo sed -i "53i $redirect" /etc/nginx/sites-available/default
sudo service nginx start
