#!/usr/bin/env bash
# a script that install nginx and change default html
sudo apt-get update -y
sudo apt-get install nginx -y
sudo -E echo "Hello World!" > /var/www/html/index.html
REDIRECT="\\\n\tlocation /redirect_me {\n\t\treturn 301 https://github.com/Bakijazzman;\n\t}\n"
sudo sed -i "53i $REDIRECT" /etc/nginx/sites-enabled/default
sudo nginx -t
sudo service nginx restart
