#!/usr/bin/env bash
# a script that install nginx and change default html
sudo apt-get update -y
sudo apt-get install nginx -y
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null
REDIRECT="\\\n\tlocation /redirect_me {\n\t\treturn 301 https://github.com/Bakijazzman;\n\t}\n"
NEW="\\\n\terror_page 404 /404.html;\n\n\tlocation = /404.html {\n\t\tinternal;\n\t}\n"
sudo sed -i "53i $REDIRECT" /etc/nginx/sites-enabled/default
sudo sed -i "53i $NEW" /etc/nginx/sites-enabled/default
sudo nginx -t
sudo service nginx restart
