#!/usr/bin/env bash
#bash script

trap love SIGNIT
trap hate SIGTERM
trap remove SIGQUIT

love()
{
	echo "Y U no love me?!"
}
remove()
{
	rm -rf /var/run/myscript.pid
	exit
}
hate()
{
	echo "I hate the kill command"
	remove
}
echo $$ > /var/run/myscript.pid
while ((1))
do
	echo "To infinity and beyond"
	sleep 2
done
